Feature#32 player functionality
BC-MAY-21-ROR/proyecto-final-pf-n21-t2 pull request #40
Opened 2022-03-15 01:04 UTC by MauricioNC

# Description
To show the video player, we send the video title to the controller and
redirect to player view.

- Player controller:
 - The controller catch the param from home view and make a request to
   get the respective video.
 - Once obtained the video, the controller iterate response and get the
   author (the user that uploaded the video) and get all the other videos
   to show them as a videos related.
 - Also, we get all the events and get the author of that event to show
   them.
  
  ## Screenshots 
![image](https://user-images.githubusercontent.com/42758875/158285613-5a715efd-94a5-4f21-a9e8-b7135b4d967b.png)
![image](https://user-images.githubusercontent.com/42758875/158285657-4af7e8bc-3343-4981-859e-ab8a3c0b01b4.png)

2022-03-15 15:15 UTC, xFerchoVJ approved these changes
LGFM

2022-03-15 16:45 UTC, LuisGomez89 approved these changes

2022-03-15 16:53 UTC, JuanequeX requested changes

2022-03-15 16:53 UTC, JuanequeX commented on EasyLearn/app/assets/stylesheets/player.css
> +}
Add a blank line here

2022-03-15 21:05 UTC, MauricioNC commented on EasyLearn/app/assets/stylesheets/player.css
> +}
Done.

2022-03-15 22:05 UTC, javs1 approved these changes

2022-03-16 01:48 UTC, YilKanda approved these changes
LGTM!

2022-03-16 02:00 UTC, JuanequeX approved these changes
LGTM

2022-03-16 02:02 UTC, merged